spring.application.name=fitness-app-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_app
spring.datasource.username=hristo-getov
spring.datasource.password=Test1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
